path:
  ckpt_path: "/work/Git/FastSpeech2/output/ckpt/Blizzard"
  log_path: "/work/Git/FastSpeech2/output/log/Blizzard"
  result_path: "/work/Git/FastSpeech2/output/result/Blizzard"
optimizer:
  batch_size: 16
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  warm_up_step: 4000
  anneal_steps: [300000, 400000, 500000]
  anneal_rate: 0.3
step:
  total_step: 900000
  log_step: 100
  synth_step: 1000
  val_step: 1000
  save_step: 50000
finetune:
  finetune: False
  pretrained_path: "/work/"
